### ISSUE TITLE
How to send proto MessageChain to QQGroup

### ISSUE THREAD

**Issue by leinlin** [GreyElaina/python-mirai#1]
last_message = None
@sub_app.receiver(GroupMessage)
async def fudu(app: Mirai, group: Group, message: MessageChain):
    global last_message
    if last_message != None and last_message.toString() == message.toString():
        EventLogger.info(f"{message.toString()}消息已复读")
        await app.sendGroupMessage(group, message)
    else:
        if last_message != None:
            EventLogger.info(f"last_message:{last_message.toString()}")
        EventLogger.info(f"{message.toString()}消息已缓存")
        last_message = message

**Comment by GreyElaina** [comment]
这个项目早就不更新了。
